### ISSUE TITLE
Tags not Working

### ISSUE THREAD

**Issue by schmandforke** [looplab/logspout-logstash#35]
Hey there,

i don't know if i made a mistake, or not... but i passed the ENV-Variable LOGSTASH_TAGS but the Tags isn't assigned:

my docker_compose:

```
logspout-logstash:
  ports:
  - 9999:80/tcp
  environment:
    ROUTE_URIS: logstash+tcp://logstash01.int.com:6666
    LOGSTASH_TAGS: test,test2
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
  image: dockerregistry.int.com/foobar/logspout-logstash:latest
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  stdin_open: true
```

and my logstash output:

```
{"message":"x.x.x.x - - [26/Sep/2016:18:45:38 +0000] \"GET / HTTP/1.0\" 200 6286 \"-\" \"-\" \"-\"","stream":"stdout","docker":{"name":"/r-buttons-microservice","id":"ddd2a2dc7c00714461826f43c19ad918261ae653efcd2c679d93a6758db95318","image":"dockerregistry.int.com/foobar/docker_image-buttons-microservice:latest","hostname":"ddd2a2dc7c00"},"tags":[],"@version":"1","@timestamp":"2016-09-26T18:45:38.368Z","host":"x.x.x.x","port":59889,"type":"docker_events"}
```

Can somebody look into ? 

Thanks
